# Generated by Django 5.0.2 on 2026-05-13 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='Prenotazioni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inizio', models.DateTimeField()),
                ('fine', models.DateTimeField()),
                ('stato_caparra', models.CharField(choices=[('DA_PAGARE', 'Da pagare'), ('DA_RESTITUIRE', 'Da restituire'), ('COMPLETATO', 'Completato')], default='DA_PAGARE', max_length=20)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prenotazioni', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('cliente', 'inizio', 'fine')},
            },
        ),
        migrations.CreateModel(
            name='Recensioni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valutazione', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('titolo', models.CharField(max_length=255)),
                ('testo', models.TextField()),
                ('approvata', models.BooleanField(default=False)),
                ('creata_il', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recensioni', to=settings.AUTH_USER_MODEL)),
                ('prenotazione', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.prenotazioni')),
            ],
        ),
    ]
