# Generated by Django 5.0.2 on 2026-05-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenPrenotazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'token_prenotazione',
            },
        ),
    ]
