# Generated by Django 5.0.2 on 2026-05-26 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tokenprenotazione'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenprenotazione',
            name='creato_il',
        ),
    ]
